name: Build LaTeX Resume

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'Makefile'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk

    - name: Build Resume with pdflatex
      run: |
        mkdir -p build
        cd src
        pdflatex -interaction=nonstopmode -output-directory=../build miserak_david-cv.tex
        pdflatex -interaction=nonstopmode -output-directory=../build miserak_david-cv.tex  # Run twice for references

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: build/miserak_david-cv.pdf
        retention-days: 7

    # Optional: Create release with PDF when tagged
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/miserak_david-cv.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
